name = "anonymous-bbs-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "bbs-db"
database_id = "d177016f-44b7-4db4-8ac2-e27c0404b06e"

[vars]
# ADMIN_EMAIL = "your-email@example.com" # Use 'wrangler secret put ADMIN_EMAIL'
# ADMIN_KEY = "your-uuid-key" # Use 'wrangler secret put ADMIN_KEY'
